name: Summarizing Experiments
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          cache: 'pip'

      - name: install the dependencies
        run: pip install -r requirements.txt

      - name: summarize the project content
        run: python -u hello_world.py
        env:
          OUTPUT_FILE_TXT: ${{ secrets.OUTPUT_FILE_TXT }}
          SOURCE_FILE_TXT: ${{ secrets.SOURCE_FILE_TXT }}

      - name: commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4